#!/usr/bin/env bash

if ! [ -f "$1" ]; then
	exit 1
fi

cache="$HOME/.cache/vidthumb"
index="$cache/index.json"
movie="$(realpath "$1")"

mkdir -p "$cache"

if [ -f "$index" ]; then
	thumbnail="$(jq -r ". \"$movie\"" <"$index")"
	if [[ "$thumbnail" != "null" ]]; then
		if [[ ! -f "$cache/$thumbnail" ]]; then
			exit 1
		fi
		echo "$cache/$thumbnail"
		exit 0
	fi
fi

thumbnail="$(uuidgen).jpg"

generate ()
{
	ffmpegthumbnailer -i "$movie" -o "/tmp/image-$thumbnail" -s 0 && \
	DATA=$($HOME/jellyfin.sh "$movie" 2>/tmp/$thumbnail.txt) && \
	printf "![](file:///tmp/image-$thumbnail)\n$DATA\n\n$(cat /tmp/$thumbnail.txt)" > "/tmp/$thumbnail.md" && \
	pandoc -f markdown -o "/tmp/$thumbnail.pdf" "/tmp/$thumbnail.md" && \
	pdftoppm "/tmp/$thumbnail.pdf" "/tmp/output" -jpeg && \
	convert "/tmp/output-1.jpg" -crop 750x500+265+255 "$cache/$thumbnail" || \
	return 1
	return 0
}

if ! generate; then
	exit 1
fi

if [[ ! -f "$index" ]]; then
	echo "{\"$movie\": \"$thumbnail\"}" >"$index"
fi
json="$(jq -r --arg "$movie" "$thumbnail" ". + {\"$movie\": \"$thumbnail\"}" <"$index")"
echo "$json" >"$index"

echo "$cache/$thumbnail"
